
FROM ubuntu:16.04

RUN apt-get update && apt-get -y install \
    wget \
    make \
    gcc 




# lets get miniconda to do installs
RUN wget  --no-check-certificate https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
RUN chmod +x Miniconda3-latest-Linux-x86_64.sh
RUN bash Miniconda3-latest-Linux-x86_64.sh -b -p /usr/miniconda3
ENV PATH /usr/miniconda3/bin:$PATH
RUN conda config --add channels r
RUN conda config --add channels conda-forge
RUN conda config --add channels bioconda

#install fastp
RUN conda install -c bioconda fastp --yes
